server:
  port: 8081

spring:
  application:
    name: user-service
  profiles:
    active: local
  config:
    import:
      - classpath:application-secret.yml

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.yoganavi.auth: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE